name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        name: Setup Go
        with:
          go-version-file: "./go.mod"
          cache: true
        id: go

      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Change postgres password
        run: |
          sudo -u postgres -p postgres psql --command="ALTER USER postgres WITH PASSWORD 'password'" --command="\du"

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
